### ISSUE TITLE
Bereitstellung IDE

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#10]
JDK 1.8 - 32Bit
Eclipse IDE for Java EE Developers - 32Bit

MySQL
https://bitnami.com/stack/nginx

GitHub for Windows
https://windows.github.com/
	GitHub Repository klonen
	https://github.com/janikvonrotz/issue-manager
	
Windows Paket Manager
https://chocolatey.org/
	Gradle installieren
	cmd -> choco install gradle

**Comment by thvn** [comment]
Auf Wunsch des Teams gibt es kein Image, sondern die Tools werden sauber mit Links in OneNote aufgelistet. Bei Problemen mit Installation oder Version, bitte auf mich zukommen.
