### ISSUE TITLE
Client GUI skizzieren

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#11]
Digitales Mockup erstellen unter berücksichtigung Multiple Scenes: https://mxshrestha.wordpress.com/2011/03/23/managing-multiple-scenes-in-javafx/

**Comment by janikvonrotz** [comment]
Digitales Mockup erstellen unter berücksichtigung Multiple Scenes: https://mxshrestha.wordpress.com/2011/03/23/managing-multiple-scenes-in-javafx/

**Comment by janikvonrotz** [comment]
Cooles Mokup tool: https://moqups.com

**Comment by RenoMeyer** [comment]
Leute, hab mal ein erstes Mockup auf OneNote geposted (Konzepte/GUI), wäre cool, wenn ihr schon mal erstes Feedback abgeben könnted über Ostern... Cheerio

**Comment by sandroklarer** [comment]
Meiner Meinung nach sieht es sehr gut aus.

**Comment by thvn** [comment]
Noch ein GUI-Vorschlag für die Stammdatenpflege (ebenfalls auf OneNote => Konzepte/GUI)
