### ISSUE TITLE
Models implementieren

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#17]
Java Implementierung des Klassenmodells

**Comment by janikvonrotz** [comment]
@NotNull beim Attribut entsprechend setzen.

**Comment by RenoMeyer** [comment]
Jeweils 2 Konstruktoren (leer und alle Parameter)

**Comment by janikvonrotz** [comment]
Es müssen keine Getter und Setter Methoden implementiert werden, hier nachlesen: https://janikvonrotz.ch/2015/03/28/build-a-java-3-tier-application-from-scratch-part-2-model-setup/

**Comment by janikvonrotz** [comment]
Gab noch ein Update im Klassenmodell: Ein Login kann nur eine Rolle haben und nicht mehrere. Umgekehrt kann eine Rolle zu mehreren Logins zugeordnet werden. Der Mangelstatus kann jetzt für mehrere Rollen verfügbar gemacht werden.
Schauen das dann noch genauer an ;)
