### ISSUE TITLE
Berechtigungskonzept erstellen

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#18]
Mehrdimensionale Tabelle mit:

Funktion: Sachbearbeiter, Kontakt, Bauherr
Berechtigung: Create, Read, Update, Delete (CRUD)
Objekt: Projekt, Mangel, Rolle, Kontakt, etc.

**Comment by thvn** [comment]
Edits:
- Delete raus!
- Kontaktadmin erhält zusätzlich die gleichen Rechte wie die Kontaktperson
- Attribut "archiviert" für Projekt

**Comment by RenoMeyer** [comment]
BerechtigungsMatrix wird am 23.4. vorgestellt, zwecks Grundlage für Berechtigungen in der App...

**Comment by janikvonrotz** [comment]
Matrix mit folgenden Entities ergänzen:

Adresse
Arbeitstyp
Mangelstatus
Ort
Person
Projektleitung
Projekttyp
Rolle
Unternehmen

Und application.json ergänzen via Permissions.csv

**Comment by RenoMeyer** [comment]
Projektleitung ist drin, der Rest wird default-mässig mit authenticated gehandhabt...

Für weitere Änderungen befindet sich eine Anleitung auf OneNote unter Konzepte/Permission
