### ISSUE TITLE
Definition Requirements

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#2]

**Comment by janikvonrotz** [comment]
Vergleichsweise wenig Requirements, andere haben über 40. Jedoch stellt sich die Frage ob wir so viele brauchen. In einer Anfangsphase lohnt es sich den Detailierungsgrad gering zu halten, damit die Kreativität bei den Problemlösungen nicht zu kurz kommt.
Wir werden diese Liste weiter verarbeiten und laufend anpassen.
D.h. wir brauchen einen sauberen Worfklow zur Anpassung der Requirements.

**Comment by janikvonrotz** [comment]
Zur Weiterverarbeitung müssen die Requirements in Funktionale und nicht Funktionale Requirements eingestuft werden.

**Comment by janikvonrotz** [comment]
https://onedrive.live.com/edit.aspx/Education/HSLU/Semester2/Softwarekomponenten/Issue-Manager/Project?cid=c4ced53321dafa52&id=documents?&wd=target%28Konzepte.one%7cA3396155-CC42-437F-9020-E7D30C5015B8%2fStrategie%7cCECB48EF-9872-4A91-B67F-93F5C5393981%2f%29
onenote:https://d.docs.live.net/c4ced53321dafa52/Education/HSLU/Semester2/Softwarekomponenten/Issue-Manager/Project/Konzepte.one#Strategie&section-id={A3396155-CC42-437F-9020-E7D30C5015B8}&page-id={CECB48EF-9872-4A91-B67F-93F5C5393981}&end

**Comment by erwinwilli** [comment]
Requirement für Authentifizierung erstellt

**Comment by janikvonrotz** [comment]
Habe meine Requirements hinzugefügt. Müssen Projekt bezogene bzw. die Ausgangslage in der Dokumentation enthalten sein?

**Comment by erwinwilli** [comment]
Habe meine Requirements angepasst und hinzugefügt.

**Comment by psoleh** [comment]
Design Requirements und Beschreibungen im IM_Requirements (extract) ergänzt

**Comment by janikvonrotz** [comment]
@Patrick: Entsprechend dem Dokument gibt es noch weitere Requirements:
 Inputs für GUI:
* Filterung von Daten über Tabellen
  * Soriterung
  * Fuzzy Search
* Geführte Navigation (gehört zu einer bedienbaren Applikation)
  * Bei Tab wechsel soll gefragt werden ob alles gespeichert worden ist
  * Die Eingabeformulare müssen validiert werden
  * Bei verstoss gegen die Dateintegrität soll gewarnt werden
  * Bei Löschung den Benutzer warnen.

**Comment by thvn** [comment]
Im nächsten Meeting müssen wir dieses Thema abschliessen. Habs im OneNote unter Kommunikation schon mal als Traktandum aufgenommen.
