### ISSUE TITLE
Model Sachbearbeiter, Rolle und Mangelstatus

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#25]

**Comment by sandroklarer** [comment]
Added Model Login and Kommentierung

**Comment by janikvonrotz** [comment]
Attribute: id, name, vorname, email von Sachberarbeiter entfernen. Werden von Person geerbt. Immer betr. Fehlermeldungen prüfen.

**Comment by erwinwilli** [comment]
Habe es angepasst.

**Comment by janikvonrotz** [comment]
Tut mir leid, es stimmt immer noch nicht alles. Im benutzerdefinierten Konstruktor muss du den benutzerdefinierten Konstruktor der Superklasse aufrufen. Die Attribute sind dabei keinenfalls vom Typ Person sondern vom Typ String.
