### ISSUE TITLE
Model Bauleiter, Projektleitung und Bauherr

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#26]
Bauleiter ohne Referenz auf Unternehmen

**Comment by thvn** [comment]
Models sind implementiert, aber muss noch reviewt werden.

**Comment by janikvonrotz** [comment]
Attribute: id, name, vorname, email von Bauleiter und Bauherr entfernen. Diese werden von der Klasse Person geerbt

**Comment by janikvonrotz** [comment]
Immer betr. Fehlermeldungen prüfen!

**Comment by janikvonrotz** [comment]
Des weiteren: Im benutzerdefinierten Konstruktor muss du den benutzerdefinierten Konstruktor der Superklasse aufrufen. Die Attribute sind dabei keinenfalls vom Typ Person sondern vom Typ String.

**Comment by thvn** [comment]
ups sorry ma homie ;D ist nun gefixt. bitte kurz überprüfen.

**Comment by janikvonrotz** [comment]
Löschweitergabe bei Referenz auf Unternehmen ergänzen

**Comment by thvn** [comment]
Cascade ist ergänzt.

**Comment by janikvonrotz** [comment]
Hast noch Warnungen auf deiner Klasse

**Comment by janikvonrotz** [comment]
Und was ist mit dem Kalendar, bitte halte dich ans Klassenmodell

**Comment by thvn** [comment]
scheiss janik -.-

**Comment by janikvonrotz** [comment]
Cascade Type bei Bauherr bitte noch ergänzen ;)
