### ISSUE TITLE
Model Projekt, Arbeitstyp und Projekttyp

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#27]

**Comment by RenoMeyer** [comment]
Meines Erachtens sollten die Attribute "projektleitungen" und "bauherr" der Klasse Projekt auch null sein können?!

**Comment by RenoMeyer** [comment]
...(Erklärung:) da beim Erfassen des Projekts dies vielleicht noch nicht unbedingt klar ist.

**Comment by janikvonrotz** [comment]
Löschweitergabe Adresse ergänzen

**Comment by janikvonrotz** [comment]
Auch bei Projektleitung machen, auch wenn Projekt nicht gelöscht wird. Macht halt einfach Sinn.
