### ISSUE TITLE
Datenmodell erstellen

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#3]

**Comment by janikvonrotz** [comment]
Hier bitte SQL tables dokumentieren:

https://onedrive.live.com/edit.aspx/Education/HSLU/Semester2/Softwarekomponenten/Issue-Manager/Project?cid=c4ced53321dafa52&id=documents?&wd=target%28Project%20Resources.one%7cC9642AD9-E770-4EB2-9E35-C78F3E250E31%2fSQL%20Database%7cCECB48EF-9872-4A91-B67F-93F5C5393981%2f%29
onenote:https://d.docs.live.net/c4ced53321dafa52/Education/HSLU/Semester2/Softwarekomponenten/Issue-Manager/Project/Project%20Resources.one#SQL%20Database&section-id={C9642AD9-E770-4EB2-9E35-C78F3E250E31}&page-id={CECB48EF-9872-4A91-B67F-93F5C5393981}&end

**Comment by erwinwilli** [comment]
Anpassung Datenmodell

**Comment by janikvonrotz** [comment]
Anstatt Subunternehmen is a User -> Kontakt is a User

**Comment by janikvonrotz** [comment]
Evtl. brauchen wir das Generalunternehmen ebenfalls nicht

**Comment by erwinwilli** [comment]
Übertragen von Visio in Workbench

**Comment by janikvonrotz** [comment]
@janik
Abklären Vererbung User, Person und Unternehmen
Wie Ortschaften Erfassen

@Übertrag Workbench
Mit Attributen

**Comment by janikvonrotz** [comment]
Tendiere dazu die Person als Interface namens Nameable zu definieren. Also bennenbar.

Interface Nameable{
  public getFullname();
}

Das Interface wird im Login implementiert

Das Interface mach vor allem beim Kommentar Sinn. Als Author eines Kommentar kann man einfach die oben gezeigt Methode aufrufen.

Andereseit möchte ich auch den anderen Fall anschauen

Spricht Login als Interface.

Setzt vorauss, das Sachbearbeiter, Subunternehmen und Bauleiter selber username und passwort felder definieren. Dafür könnte man vorname, nachname für alle Personen (bauleiter, sachbearbeiter, kontakt, bauherr.

Da könnte man auch Unternemen als Superklasse definieren -> Bauherr extends Unternehmen
Unternehmen extends Person

**Comment by janikvonrotz** [comment]
Habe das Modell überarbeitet, was hälst du davon? Nameable ist ein Interface, dass nur bei der Implementierung vorkommt, für das Datenmodell kannst du es weglassen

**Comment by janikvonrotz** [comment]
Da wir keine Datenbank modellieren müssen, könnten wir direkt das Klassenmodell erstellen, mit allen Methoden, Attributen und Interfaces.

Gute Idee oder Schlechte Idee?

IM_Klassenmodell.vsdx

**Comment by janikvonrotz** [comment]
Frage die wir noch kären müssen: ist ein SU-MA eine Ansprechperson

**Comment by janikvonrotz** [comment]
Ich würde sagen Ja. Jedes Login muss einer Person zuweisbar sein, damit Aktionen zuweisbar sind.

**Comment by RenoMeyer** [comment]
Gefällt mir gut, habe noch die folgenden Änderungen vorgenommen (bitte checken, ob es korrekt ist!):

- Bauleiter extends Nameable
- Ort -> Adresse: würde vorschlagen wir halten es vorerst simple, d.h. manuelle Eingabe aller Adressdetails
- 1 to 1 Beziehung zwischen Projekt und Adresse
- Ebenfalls 1 to 1 Beziehung zwischen Unternehmung und Adresse

Frage: wie ist die Beziehung zwischen Unternehmung und Bauherr zu verstehen?

**Comment by janikvonrotz** [comment]
Ups, gab grosse änderungen meinerseits
Werde deine Anpassungen einbauen

**Comment by janikvonrotz** [comment]
Adresse besteht aus: Strasse und Ort oder nicht. Strasse wird im Projekt eingetragen und dann in einer Auswahlbox die Ortschaft

**Comment by janikvonrotz** [comment]
Braucht die Unternehmung eine Adresse mit Ort?

**Comment by RenoMeyer** [comment]
Ja, Unternehumng braucht eine Adresse; es heisst dass alle geschäftsrelevanten Daten erfasst werden müssen. Adresse braucht man z.B. für Rechnungen, Verträge, etc. Das bedeutet übrigens auch, dass der Bauherr in jedem Fall eine Adresse braucht, ob er nun eine Privatperson oder der Kontakt in einer Unternehmung ist!

**Comment by erwinwilli** [comment]
Habe mal ein erstes Klassenmodell erstellt. könnt es ja mal anschauen. 
Muss aber noch mit Janik etwas anschauen.

**Comment by RenoMeyer** [comment]
Hab das Gefühl bei Mangel fehlt noch der FK Mangelstatus?!? Kann das jemand bestätigen?

**Comment by janikvonrotz** [comment]
Danke für den Hinweis, habs angepasst

**Comment by RenoMeyer** [comment]
Aathi und ich finden, es bräuchte noch Telefonnummer-Attribute für alle Personen (kann null sein), was meint ihr?

**Comment by RenoMeyer** [comment]
Desweiteren, es braucht noch ein "Erledigungsdatum" (oder Frist, oder was auch immer) beim Mangel!

**Comment by RenoMeyer** [comment]
Projekt braucht noch "Start" und "End" Daten (vgl. Aufgabenstellung)

**Comment by janikvonrotz** [comment]
Alles ausser Telefonnummer angepasst

**Comment by RenoMeyer** [comment]
Schlage vor, dass Projekt, Mangel und Kommentar einen Timestamp bekommen (Attribut "erstellt am" oder so...)
