### ISSUE TITLE
Seed Task implementieren

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#31]
Für Aufgaben siehe Seed Klasse:

Aufwand ca. 3 Stunden

**Comment by janikvonrotz** [comment]
Cascade Delete funktioniert nuni, z.B. weme es unternehme löscht wird d Adressse nid glöscht. Vilicht gfindsch epis use

**Comment by erwinwilli** [comment]
@jannik Hast du per Zufall etwas noch nicht commited?
Ich bekomme immer noch die Fehlermeldung von wegem "unknown column archiviert"

**Comment by janikvonrotz** [comment]
Habe im application.json das drop-with herausgenommen. Lösch mal alle Tabellen in der DB im phpmyadmin

**Comment by erwinwilli** [comment]
Anpassen des SeedTask:
Feld mangel bei Mangel hinzugefügt (Mangelbeschreibung)
