### ISSUE TITLE
Loggingframework konfigurieren

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#35]
Tool: http://www.tinylog.org/download
Loging Facade: slf4j
Implementierung Logger: http://projectlombok.org/features/Log.html

Ziel: Erstellen einfaches Logging -> Beispiel

**Comment by thvn** [comment]
Wohin soll geloggt werden?
- ConsoleWriter ..denke nicht :D
- FileWriter
- JdbcWriter ..würde sinn machen
- RollingFileWriter
- SharedFileWriter ..sounds intresting!

**Comment by janikvonrotz** [comment]
http://jira.qos.ch/browse/LOGBACK-557

**Comment by thvn** [comment]
Logging ist für IssueManager (Webservices) implementiert. Elemente können jetzt einfach hinzugefügt werden:

Bsp:
log.error(String, Object);
catch (Exception e){
			log.error("RMI initialize failed.", e);
}
