### ISSUE TITLE
CRUD Filterung auf Webservice

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#41]
Wo nötig müssen CRUD Zugriffe auf dem Webservice gefiltert werden.

**Comment by janikvonrotz** [comment]
LoginFilter: Wenn rolle nicht Sachbearbeiter dürfen nur eigene Logins persistiert werden -> vergleich anhand ID.

**Comment by erwinwilli** [comment]
LoginFilter erstellt.

**Comment by janikvonrotz** [comment]
Bitte noch für deleteAll() und getAllByProperty Methoden ergänzen. DeleteAll darf nur der Sachbearbeiter. GetAllByProperty analog getAll erstellen

**Comment by erwinwilli** [comment]
Done.

Bim löscha bini nit sicher öpps tuat.
aswia hanis nit gschafft z powershel a z passa, damit i löscha cha. kriaga immer a fähler :(
falls is no a passa muas wills nit tuat. seisch. de machis gra :D

**Comment by janikvonrotz** [comment]
Sieht gut aus, bitte noch Source Code dokumentieren

**Comment by erwinwilli** [comment]
Code Dokumentiert

**Comment by janikvonrotz** [comment]
Erstelle  MangelFilter.java

    getAll() -> vergleich mangel.subunternehmen und kontakt.subunternehmen
    getAllByProperty -> vergleich mangel.subunternehmen und kontakt.subunternehmen

Bei den restlichen Benutzer immer alle Mangel anzeigen.

**Comment by erwinwilli** [comment]
He i cha aswia kei verglich macha. cha dia jewiliga funktiona nit a wähla bzw. uswähla :(
was machi falsch?

**Comment by janikvonrotz** [comment]
Erweitern ProjektFilter:

* Für Kontakte nur die zugeteilten Projekte anzeigen.

**Comment by erwinwilli** [comment]
Projekte Filter erstellt --> Test erfolgreich
MangelFilter erstellt --> Test erfolgreich

**Comment by janikvonrotz** [comment]
ProjektFilter mit getAllByProperty ergänzen.

**Comment by erwinwilli** [comment]
getAllByProperty ergänzt --> Test erfolgreich
