### ISSUE TITLE
Mangel Referenz Subunternehmen

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#45]
Beim Mangel fehlt noch eine Referenz auf das Subunternhmen. 
* Klassenmodell Vision anpassen
* Klasse Mangel anpassen
* Seed File anpassen

**Comment by erwinwilli** [comment]
- Klassenmodell --> angepasst
- Klasse Mangel --> angepasst
- Seed File --> angepasst

Test korrigiert, damit Sie funktionieren
