### ISSUE TITLE
Collaboration Tool evaluieren

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/issue-manager#8]
Taiga.io oder Waffle.io?

**Comment by janikvonrotz** [comment]
Bi scho mega fan worde vo Waffle, me cha eifach alles uf eim Borad erledige und d integration mit GitHub isch perfekt. Han mier erlaubt mal es paar Sache z mache.
Han milestones, labls und columns erstellt. Und üses Excel Dokument ergänzt mit de Task IDs.
Wär doch en easy Workflow.

**Comment by thvn** [comment]
finds au rächts geil. bsonders integration in github. ha trotzdem mol beidi tools gnauer vergliche und pro/contras mol ufstellt. schlussändlich muss es üsem projekt passe. wörd säge mer entscheidets bim nöchste meeting!

Waffle.io:
	+ Perfekte GitHub Integration, z.B. Issues über Commits schliessen (2-Way Sync)
	+ Einfache Bedinung
	- Issues und Tasks in einer Anzeige (kann auch Vorteil sein)
	- Keine weiteren Features (z.B. Sprints oder Rollen)

Taiga.io
	+ Innovativ
	+ Lebt agiles Managmeent
	+ Kombination zwischen Kanban und Scrum möglich (modular aufgebaut)
	+ Klare Trennung zwischen Issues (Bug reporting) und Tasks (User Storys)
	+ Viele Features und individuell anpassbar (Plugins)
	- Schlechtere GibHub Integration (Issues werden nur 1-Way gesynct und Tasks gar nicht)
